/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.e_diary;
import javax.swing.JOptionPane;

/**
 *
 * @author sarah
 */
public class E_Diary_Option extends javax.swing.JFrame {

    /**
     * Creates new form E_Diary_Form
     */
    public E_Diary_Option() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        E_Diary_Logo1 = new javax.swing.JLabel();
        Write_An_Entry = new javax.swing.JButton();
        View_Entries = new javax.swing.JButton();
        Log_Out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(532, 518));

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 10));

        E_Diary_Logo1.setBackground(new java.awt.Color(255, 102, 102));
        E_Diary_Logo1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        E_Diary_Logo1.setForeground(new java.awt.Color(255, 255, 204));
        E_Diary_Logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_Diary_Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/e_diary/download.png"))); // NOI18N
        E_Diary_Logo1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        E_Diary_Logo1.setPreferredSize(new java.awt.Dimension(89, 29));

        Write_An_Entry.setBackground(new java.awt.Color(128, 0, 128));
        Write_An_Entry.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        Write_An_Entry.setForeground(new java.awt.Color(255, 255, 204));
        Write_An_Entry.setText("Write An Entry");
        Write_An_Entry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Write_An_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Write_An_EntryActionPerformed(evt);
            }
        });

        View_Entries.setBackground(new java.awt.Color(128, 0, 128));
        View_Entries.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        View_Entries.setForeground(new java.awt.Color(255, 255, 204));
        View_Entries.setText("View Entries");
        View_Entries.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        View_Entries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_EntriesActionPerformed(evt);
            }
        });

        Log_Out.setBackground(new java.awt.Color(128, 0, 128));
        Log_Out.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        Log_Out.setForeground(new java.awt.Color(255, 255, 204));
        Log_Out.setText("Log - Out");
        Log_Out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_OutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(View_Entries, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Write_An_Entry))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(E_Diary_Logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(E_Diary_Logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Write_An_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(View_Entries, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Write_An_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Write_An_EntryActionPerformed
    this.dispose();
    E_Diary_Write write = new E_Diary_Write();
    write.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_Write_An_EntryActionPerformed

    private void View_EntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_EntriesActionPerformed
    this.dispose();
    E_Diary_View view = new E_Diary_View();
    view.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_View_EntriesActionPerformed

    private void Log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_OutActionPerformed
        {
            JOptionPane.showMessageDialog(this, "Logged - Out Successfully");
            this.dispose();
            E_Diary_Log_In log = new E_Diary_Log_In();
            log.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_Log_OutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_Diary_Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel E_Diary_Logo1;
    private javax.swing.JButton Log_Out;
    private javax.swing.JButton View_Entries;
    private javax.swing.JButton Write_An_Entry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
