/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.e_diary;

import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author sarah
 */
public class E_Diary_View extends javax.swing.JFrame {

    Connection con;
    PreparedStatement st;
    ResultSet rst;
    
    /**
     * Creates new form E_Diary_View
     */
    public E_Diary_View() {
        initComponents();
        Connect_SQL();
    }

    public void Connect_SQL()
    {
      try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/e_diary_data", "root", "");
        } 
      
      catch (ClassNotFoundException | SQLException ex) 
        {
            Logger.getLogger(E_Diary_Write.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Enter_the_Date = new javax.swing.JLabel();
        Event_Title = new javax.swing.JLabel();
        Mood = new javax.swing.JLabel();
        Event_Details = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Event_Details_Area = new javax.swing.JTextArea();
        Date_Field = new javax.swing.JTextField();
        Month_Field = new javax.swing.JTextField();
        Year_Field = new javax.swing.JTextField();
        Title_Field = new javax.swing.JTextField();
        Mood_Field = new javax.swing.JTextField();
        Get_Data = new javax.swing.JButton();
        Go_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 10));

        Enter_the_Date.setBackground(new java.awt.Color(204, 0, 0));
        Enter_the_Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Enter_the_Date.setForeground(new java.awt.Color(128, 0, 128));
        Enter_the_Date.setText("Enter the date:");
        Enter_the_Date.setMaximumSize(new java.awt.Dimension(101, 17));
        Enter_the_Date.setMinimumSize(new java.awt.Dimension(101, 17));
        Enter_the_Date.setPreferredSize(new java.awt.Dimension(101, 17));

        Event_Title.setBackground(new java.awt.Color(204, 0, 0));
        Event_Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Event_Title.setForeground(new java.awt.Color(128, 0, 128));
        Event_Title.setText("Event Title:");
        Event_Title.setMaximumSize(new java.awt.Dimension(101, 17));
        Event_Title.setMinimumSize(new java.awt.Dimension(101, 17));
        Event_Title.setPreferredSize(new java.awt.Dimension(101, 17));

        Mood.setBackground(new java.awt.Color(204, 0, 0));
        Mood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mood.setForeground(new java.awt.Color(128, 0, 128));
        Mood.setText("Mood:");
        Mood.setMaximumSize(new java.awt.Dimension(101, 17));
        Mood.setMinimumSize(new java.awt.Dimension(101, 17));
        Mood.setPreferredSize(new java.awt.Dimension(101, 17));

        Event_Details.setBackground(new java.awt.Color(204, 0, 0));
        Event_Details.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Event_Details.setForeground(new java.awt.Color(128, 0, 128));
        Event_Details.setText("Event Details:");
        Event_Details.setMaximumSize(new java.awt.Dimension(101, 17));
        Event_Details.setMinimumSize(new java.awt.Dimension(101, 17));
        Event_Details.setPreferredSize(new java.awt.Dimension(101, 17));

        Event_Details_Area.setBackground(new java.awt.Color(102, 51, 153));
        Event_Details_Area.setColumns(20);
        Event_Details_Area.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Event_Details_Area.setForeground(new java.awt.Color(255, 255, 204));
        Event_Details_Area.setRows(5);
        jScrollPane1.setViewportView(Event_Details_Area);

        Date_Field.setBackground(new java.awt.Color(102, 51, 153));
        Date_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Date_Field.setForeground(new java.awt.Color(255, 255, 204));
        Date_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date_Field.setText("DD");

        Month_Field.setBackground(new java.awt.Color(102, 51, 153));
        Month_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Month_Field.setForeground(new java.awt.Color(255, 255, 204));
        Month_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Month_Field.setText("Month");

        Year_Field.setBackground(new java.awt.Color(102, 51, 153));
        Year_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Year_Field.setForeground(new java.awt.Color(255, 255, 204));
        Year_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Year_Field.setText("YYYY");

        Title_Field.setBackground(new java.awt.Color(102, 51, 153));
        Title_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Title_Field.setForeground(new java.awt.Color(255, 255, 204));
        Title_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Title_Field.setText("....");

        Mood_Field.setBackground(new java.awt.Color(102, 51, 153));
        Mood_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mood_Field.setForeground(new java.awt.Color(255, 255, 204));
        Mood_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mood_Field.setText("....");

        Get_Data.setBackground(new java.awt.Color(128, 0, 128));
        Get_Data.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Get_Data.setForeground(new java.awt.Color(255, 255, 204));
        Get_Data.setText("Get Data");
        Get_Data.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Get_Data.setMaximumSize(new java.awt.Dimension(72, 22));
        Get_Data.setMinimumSize(new java.awt.Dimension(72, 22));
        Get_Data.setPreferredSize(new java.awt.Dimension(72, 22));
        Get_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Get_DataActionPerformed(evt);
            }
        });

        Go_Back.setBackground(new java.awt.Color(128, 0, 128));
        Go_Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go_Back.setForeground(new java.awt.Color(255, 255, 204));
        Go_Back.setText("Go Back");
        Go_Back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Go_Back.setMaximumSize(new java.awt.Dimension(72, 22));
        Go_Back.setMinimumSize(new java.awt.Dimension(72, 22));
        Go_Back.setPreferredSize(new java.awt.Dimension(72, 22));
        Go_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Enter_the_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(Event_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Event_Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Title_Field)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Date_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Month_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Year_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Mood_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Get_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Go_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enter_the_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Event_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mood, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mood_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Event_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Get_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Go_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_BackActionPerformed
    this.dispose();
    E_Diary_Option opt = new E_Diary_Option();
    opt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_Go_BackActionPerformed

    private void Get_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Get_DataActionPerformed
    int date = Integer.parseInt(Date_Field.getText());
    String month = Month_Field.getText();
    int year = Integer.parseInt(Year_Field.getText());  
    
    String[] month1 = {"Januaray", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};

    int date_flag = 0;
    int month_flag = 1;
    int year_flag = 0;

    if (date>=1 && date<=31)
    {

    }

    else
    {
        date_flag = 1;
    }

    for (int n = 0; n<12; n++)
    {
        if (month1[n].equals(month))
        {
            month_flag = 0;
            break;
        }
    }

    if (year>=2022 && year<=2024)
    {

    }

    else
    {
        year_flag = 1;
    }
        
        

    if (date_flag == 1 || month_flag == 1 || year_flag == 1)
    {
        JOptionPane.showMessageDialog(this, "Invalid Date/Month/Year. Enter the date and year in numeric form and month in alphabetical form.");
    }
        
    }//GEN-LAST:event_Get_DataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Diary_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Diary_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Diary_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Diary_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_Diary_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date_Field;
    private javax.swing.JLabel Enter_the_Date;
    private javax.swing.JLabel Event_Details;
    private javax.swing.JTextArea Event_Details_Area;
    private javax.swing.JLabel Event_Title;
    private javax.swing.JButton Get_Data;
    private javax.swing.JButton Go_Back;
    private javax.swing.JTextField Month_Field;
    private javax.swing.JLabel Mood;
    private javax.swing.JTextField Mood_Field;
    private javax.swing.JTextField Title_Field;
    private javax.swing.JTextField Year_Field;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
