/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.e_diary;
import javax.swing.JOptionPane;
/**
 *
 * @author sarah
 */
public class E_Diary_Log_In extends javax.swing.JFrame {

    /**
     * Creates new form E_Diary_UI
     */
    public E_Diary_Log_In() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        E_Diary_Logo = new javax.swing.JLabel();
        Log_In = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Username_Enter = new javax.swing.JTextField();
        Password_Enter = new javax.swing.JTextField();
        Sign_In = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(532, 518));

        E_Diary_Logo.setBackground(new java.awt.Color(255, 102, 102));
        E_Diary_Logo.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        E_Diary_Logo.setForeground(new java.awt.Color(255, 255, 204));
        E_Diary_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_Diary_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/e_diary/download.png"))); // NOI18N
        E_Diary_Logo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        E_Diary_Logo.setMinimumSize(new java.awt.Dimension(642, 500));
        E_Diary_Logo.setPreferredSize(new java.awt.Dimension(89, 29));

        Log_In.setBackground(new java.awt.Color(128, 0, 128));
        Log_In.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Log_In.setForeground(new java.awt.Color(128, 0, 128));
        Log_In.setText("Log - In");

        Username.setBackground(new java.awt.Color(128, 0, 128));
        Username.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(128, 0, 128));
        Username.setText("Username:");

        Password.setBackground(new java.awt.Color(128, 0, 128));
        Password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(128, 0, 128));
        Password.setText("Password:");

        Username_Enter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Username_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_EnterActionPerformed(evt);
            }
        });

        Password_Enter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Password_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_EnterActionPerformed(evt);
            }
        });

        Sign_In.setBackground(new java.awt.Color(128, 0, 128));
        Sign_In.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Sign_In.setForeground(new java.awt.Color(255, 255, 204));
        Sign_In.setText("Sign - In");
        Sign_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_InActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(128, 0, 128));
        Exit.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 204));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Log_In, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(E_Diary_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Password)
                                .addGap(24, 24, 24)
                                .addComponent(Password_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Username)
                                .addGap(18, 18, 18)
                                .addComponent(Username_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(Sign_In, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Exit)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Log_In, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(E_Diary_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Username_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Password_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sign_In)
                    .addComponent(Exit))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_EnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_EnterActionPerformed

    private void Sign_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_InActionPerformed
    String user_name = Username_Enter.getText();
    String pass_word = Password_Enter.getText();

    if ("Group39".equals(user_name) && "Group39".equals(pass_word))   
    {
    JOptionPane.showMessageDialog(this, "Log - In Successful");
    this.dispose();
    E_Diary_Option opt = new E_Diary_Option();
    opt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_Sign_InActionPerformed

    else
    {
        JOptionPane.showMessageDialog(this, "Invalid Credentials. Log - In Unsuccessful");
    }
    }
    private void Password_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_EnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_EnterActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                E_Diary_Log_In log_in = new E_Diary_Log_In();
                log_in.setVisible(true);
                log_in.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel E_Diary_Logo;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Log_In;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField Password_Enter;
    private javax.swing.JButton Sign_In;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Username_Enter;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
