/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.e_diary;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author sarah
 */
public class E_Diary_Write extends javax.swing.JFrame {

    Connection con;
    PreparedStatement st;
    
    /**
     * Creates new form E_Diary_Write
     */
    
    public E_Diary_Write() {
        initComponents();
        Connect_SQL();
        
    }
    
    public void Connect_SQL()
    {
      try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/e_diary_data", "root", "");
        } 
      
      catch (ClassNotFoundException | SQLException ex) 
        {
            Logger.getLogger(E_Diary_Write.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Date_Of_Entry = new javax.swing.JLabel();
        Event_Title = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        Event_Details = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Event_Details_Area = new javax.swing.JTextArea();
        Event_Title2 = new javax.swing.JLabel();
        Event_Title3 = new javax.swing.JLabel();
        Image_Box = new javax.swing.JLabel();
        Upload = new javax.swing.JButton();
        Add_Entry = new javax.swing.JButton();
        Go_Back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Date_Field = new javax.swing.JTextField();
        Month_Field = new javax.swing.JTextField();
        Year_Field = new javax.swing.JTextField();
        Mood_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(532, 518));

        Date_Of_Entry.setBackground(new java.awt.Color(204, 0, 0));
        Date_Of_Entry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Date_Of_Entry.setForeground(new java.awt.Color(128, 0, 128));
        Date_Of_Entry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date_Of_Entry.setText("Date of Entry: ");

        Event_Title.setBackground(new java.awt.Color(204, 0, 0));
        Event_Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Event_Title.setForeground(new java.awt.Color(128, 0, 128));
        Event_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Event_Title.setText("Event Title: ");

        Title.setBackground(new java.awt.Color(102, 51, 153));
        Title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 204));

        Event_Details.setBackground(new java.awt.Color(204, 0, 0));
        Event_Details.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Event_Details.setForeground(new java.awt.Color(128, 0, 128));
        Event_Details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Event_Details.setText("Event Details: ");

        Event_Details_Area.setBackground(new java.awt.Color(102, 51, 153));
        Event_Details_Area.setColumns(20);
        Event_Details_Area.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Event_Details_Area.setForeground(new java.awt.Color(255, 255, 204));
        Event_Details_Area.setRows(5);
        jScrollPane1.setViewportView(Event_Details_Area);

        Event_Title2.setBackground(new java.awt.Color(204, 0, 0));
        Event_Title2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Event_Title2.setForeground(new java.awt.Color(128, 0, 128));
        Event_Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Event_Title2.setText("Image: ");

        Event_Title3.setBackground(new java.awt.Color(204, 0, 0));
        Event_Title3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Event_Title3.setForeground(new java.awt.Color(128, 0, 128));
        Event_Title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Event_Title3.setText("Mood: ");

        Image_Box.setBackground(new java.awt.Color(102, 51, 153));
        Image_Box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image_Box.setOpaque(true);

        Upload.setBackground(new java.awt.Color(128, 0, 128));
        Upload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Upload.setForeground(new java.awt.Color(255, 255, 204));
        Upload.setText("Upload");
        Upload.setToolTipText("");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        Add_Entry.setBackground(new java.awt.Color(128, 0, 128));
        Add_Entry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Add_Entry.setForeground(new java.awt.Color(255, 255, 204));
        Add_Entry.setText("Add Entry");
        Add_Entry.setToolTipText("");
        Add_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_EntryActionPerformed(evt);
            }
        });

        Go_Back.setBackground(new java.awt.Color(128, 0, 128));
        Go_Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go_Back.setForeground(new java.awt.Color(255, 255, 204));
        Go_Back.setText("Go Back");
        Go_Back.setToolTipText("");
        Go_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_BackActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(128, 0, 128));
        Clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 204));
        Clear.setText("Clear");
        Clear.setToolTipText("");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Date_Field.setBackground(new java.awt.Color(102, 51, 153));
        Date_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Date_Field.setForeground(new java.awt.Color(255, 255, 204));
        Date_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date_Field.setText("DD");
        Date_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_FieldActionPerformed(evt);
            }
        });

        Month_Field.setBackground(new java.awt.Color(102, 51, 153));
        Month_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Month_Field.setForeground(new java.awt.Color(255, 255, 204));
        Month_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Month_Field.setText("Month");
        Month_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_FieldActionPerformed(evt);
            }
        });

        Year_Field.setBackground(new java.awt.Color(102, 51, 153));
        Year_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Year_Field.setForeground(new java.awt.Color(255, 255, 204));
        Year_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Year_Field.setText("YYYY");
        Year_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year_FieldActionPerformed(evt);
            }
        });

        Mood_Field.setBackground(new java.awt.Color(102, 51, 153));
        Mood_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mood_Field.setForeground(new java.awt.Color(255, 255, 204));
        Mood_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Mood_Field.setText("....");
        Mood_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mood_FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Date_Of_Entry)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Date_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Month_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Year_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Event_Title)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(19, 19, 19)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Event_Title2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Image_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Add_Entry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Go_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Upload))))
                    .addComponent(Event_Details)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Event_Title3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mood_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date_Of_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Event_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Event_Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mood_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Event_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Add_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Go_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Image_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Event_Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mood_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mood_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mood_FieldActionPerformed

    private void Year_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_FieldActionPerformed

    private void Month_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_FieldActionPerformed

    private void Date_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_FieldActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Title.setText("");
        Event_Details_Area.setText("");
        Date_Field.setText("");
        Month_Field.setText("");
        Year_Field.setText("");
        Mood_Field.setText("");
        Image_Box.setIcon(null);
    }//GEN-LAST:event_ClearActionPerformed

    private void Go_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_BackActionPerformed
        this.dispose();
        E_Diary_Option option_back = new E_Diary_Option();
        option_back.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_Go_BackActionPerformed

    private void Add_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_EntryActionPerformed

        int date = Integer.parseInt(Date_Field.getText());
        String month = Month_Field.getText();
        int year = Integer.parseInt(Year_Field.getText());

        String title = Title.getText();
        String mood = Mood_Field.getText();
        String details = Event_Details_Area.getText();

        String[] month1 = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
        String[] mood1 = {"Happiness", "Sadness", "Fear", "Disgust", "Surprise", "Anger"};
        
        int date_flag = 0;
        int month_flag = 1;
        int year_flag = 0;
        int mood_flag = 1;

        if (date>=1 && date<=31)
        {

        }

        else
        {
            date_flag = 1;
        }

        for (int n = 0; n<12; n++)
        {
            if (month1[n].equals(month))
            {
                month_flag = 0;
                break;
            }
        }

        if (year>=2022 && year<=2025)
        {

        }

        else
        {
            year_flag = 1;
        }
        
        for (int n = 0; n<5; n++)
        {
            if (mood1[n].equals(mood))
            {
                mood_flag = 0;
                break;
            }
        }
        

        if (date_flag == 1 || month_flag == 1 || year_flag == 1)
        {
            JOptionPane.showMessageDialog(this, "Invalid Date/Month/Year. Enter the date and year in numeric form and month in alphabetical form.");
        }
        
        else if (mood_flag == 1)
        {
            JOptionPane.showMessageDialog(this, "Invalid Mood. The valid moods are: Happiness, Sadness, Fear, Surprise, Disgust, Anger.");
        }

        else
        {
            try
            {
                // Add sql query
                st = con.prepareStatement("insert into event_details(Date, Month, Year, Title, Mood, Details) values (?, ?, ?, ?, ?, ?)");
                st.setInt(1, date);
                st.setString(2, month);
                st.setInt(3, year);
                st.setString(4, title);
                st.setString(5, mood);
                st.setString(6, details);

                int e = st.executeUpdate();

                if(e == 1)
                {
                    JOptionPane.showMessageDialog(this, "Diary Entry Added");
                    Date_Field.setText("");
                    Month_Field.setText("");
                    Year_Field.setText("");
                    Title.setText("");
                    Mood_Field.setText("");
                    Event_Details_Area.setText("");
                    Image_Box.setIcon(null);
                }

                else
                {
                    JOptionPane.showMessageDialog(this, "Diary Entry Not Added");
                }

            }

            catch (SQLException ex)
            {
                Logger.getLogger(E_Diary_Write.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_EntryActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed

        JFileChooser fc = new JFileChooser();

        //Limit type of file name extensions supported.

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files (jpg, jpeg, png)", "jpg", "png", "jpeg");

        fc.setFileFilter(filter);

        int selected = fc.showOpenDialog(null);

        //check if open button has been clicked.

        if (selected == JFileChooser.APPROVE_OPTION) {

            File file = fc.getSelectedFile();

            //Get Path of the selected image.

            String getselectedImage = file.getAbsolutePath();

            //Display image path on Message Dialog

            JOptionPane.showMessageDialog(null, getselectedImage);

            ImageIcon imIco = new ImageIcon(getselectedImage);

            //make image fit on jlabel.

            Image imFit = imIco.getImage();

            Image imgFit = imFit.getScaledInstance(Image_Box.getWidth(), Image_Box.getHeight(), Image.SCALE_SMOOTH);

            Image_Box.setIcon(new ImageIcon(imgFit));

        }// TODO add your handling code here:
    }//GEN-LAST:event_UploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Diary_Write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_Diary_Write().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Entry;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Date_Field;
    private javax.swing.JLabel Date_Of_Entry;
    private javax.swing.JLabel Event_Details;
    private javax.swing.JTextArea Event_Details_Area;
    private javax.swing.JLabel Event_Title;
    private javax.swing.JLabel Event_Title2;
    private javax.swing.JLabel Event_Title3;
    private javax.swing.JButton Go_Back;
    private javax.swing.JLabel Image_Box;
    private javax.swing.JTextField Month_Field;
    private javax.swing.JTextField Mood_Field;
    private javax.swing.JTextField Title;
    private javax.swing.JButton Upload;
    private javax.swing.JTextField Year_Field;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
